[build]
  command = "npm install"
  functions = "netlify/functions/"
  publish = "netlify/functions/"
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
